In [1]:
#importing essential libraries
import numpy as np
import pandas as pd

In [2]:
#loading my netflix dataset
df = pd.read_csv("NFLX.csv")
df

Date        Open        High         Low       Close   Adj Close  \
0     2018-02-05  262.000000  267.899994  250.029999  254.259995  254.259995   
1     2018-02-06  247.699997  266.700012  245.000000  265.720001  265.720001   
2     2018-02-07  266.579987  272.450012  264.329987  264.559998  264.559998   
3     2018-02-08  267.079987  267.619995  250.000000  250.100006  250.100006   
4     2018-02-09  253.850006  255.800003  236.110001  249.470001  249.470001   
...          ...         ...         ...         ...         ...         ...   
1004  2022-01-31  401.970001  427.700012  398.200012  427.140015  427.140015   
1005  2022-02-01  432.959991  458.480011  425.540009  457.130005  457.130005   
1006  2022-02-02  448.250000  451.980011  426.480011  429.480011  429.480011   
1007  2022-02-03  421.440002  429.260010  404.279999  405.600006  405.600006   
1008  2022-02-04  407.309998  412.769989  396.640015  410.170013  410.170013   

        Volume  
0     11896100  
1     12595800  
2      8981500  
3      9306700  
4     16906900  
...        ...  
1004  20047500  
1005  22542300  
1006  14346000  
1007   9905200  
1008   7782400  

[1009 rows x 7 columns]

In [3]:
#deleting date and adj close columns
del df["Date"]
del df["Adj Close"]
df

Open        High         Low       Close    Volume
0     262.000000  267.899994  250.029999  254.259995  11896100
1     247.699997  266.700012  245.000000  265.720001  12595800
2     266.579987  272.450012  264.329987  264.559998   8981500
3     267.079987  267.619995  250.000000  250.100006   9306700
4     253.850006  255.800003  236.110001  249.470001  16906900
...          ...         ...         ...         ...       ...
1004  401.970001  427.700012  398.200012  427.140015  20047500
1005  432.959991  458.480011  425.540009  457.130005  22542300
1006  448.250000  451.980011  426.480011  429.480011  14346000
1007  421.440002  429.260010  404.279999  405.600006   9905200
1008  407.309998  412.769989  396.640015  410.170013   7782400

[1009 rows x 5 columns]

In [4]:
#seperating close column
Y = np.array(df["Close"])
Y

array([254.259995, 265.720001, 264.559998, ..., 429.480011, 405.600006,
       410.170013])

In [5]:
#deleting close column after seperating in Y variable
del df["Close"]
df

Open        High         Low    Volume
0     262.000000  267.899994  250.029999  11896100
1     247.699997  266.700012  245.000000  12595800
2     266.579987  272.450012  264.329987   8981500
3     267.079987  267.619995  250.000000   9306700
4     253.850006  255.800003  236.110001  16906900
...          ...         ...         ...       ...
1004  401.970001  427.700012  398.200012  20047500
1005  432.959991  458.480011  425.540009  22542300
1006  448.250000  451.980011  426.480011  14346000
1007  421.440002  429.260010  404.279999   9905200
1008  407.309998  412.769989  396.640015   7782400

[1009 rows x 4 columns]

In [6]:
#Converting whole dataset into 2-D array
X = df.values
X

array([[2.62000000e+02, 2.67899994e+02, 2.50029999e+02, 1.18961000e+07],
       [2.47699997e+02, 2.66700012e+02, 2.45000000e+02, 1.25958000e+07],
       [2.66579987e+02, 2.72450012e+02, 2.64329987e+02, 8.98150000e+06],
       ...,
       [4.48250000e+02, 4.51980011e+02, 4.26480011e+02, 1.43460000e+07],
       [4.21440002e+02, 4.29260010e+02, 4.04279999e+02, 9.90520000e+06],
       [4.07309998e+02, 4.12769989e+02, 3.96640015e+02, 7.78240000e+06]])

In [7]:
#importing model_selection from sklearn for spliting X and Y into training and testing
from sklearn import model_selection
X_train, X_test ,Y_train,Y_test = model_selection.train_test_split(X,Y, test_size = 0.3) 
X_train,Y_train

(array([[3.70660004e+02, 3.76000000e+02, 3.67079987e+02, 7.94340000e+06],
        [2.66579987e+02, 2.72450012e+02, 2.64329987e+02, 8.98150000e+06],
        [4.35690002e+02, 4.47000000e+02, 4.27269989e+02, 7.01460000e+06],
        ...,
        [3.10579987e+02, 3.11880005e+02, 3.05299988e+02, 6.17910000e+06],
        [6.28179993e+02, 6.39869995e+02, 6.26359985e+02, 4.58040000e+06],
        [2.71809998e+02, 2.74019989e+02, 2.68799988e+02, 4.82740000e+06]]),
 array([367.679993, 264.559998, 438.269989, 318.829987, 443.399994,
        298.600006, 678.799988, 313.299988, 540.72998 , 368.149994,
        565.169983, 495.079987, 369.75    , 410.170013, 593.26001 ,
        654.059998, 335.660004, 502.109985, 268.029999, 513.469971,
        335.829987, 494.73999 , 265.920013, 339.670013, 491.869995,
        538.849976, 326.130005, 343.429993, 604.559998, 298.929993,
        360.869995, 591.059998, 274.880005, 375.220001, 339.730011,
        275.299988, 691.690002, 411.890015, 358.820007, 512.40002

In [8]:
print(X_train.shape)
print(Y_train.shape)

(706, 4)
(706,)


In [9]:
#importing Linear Regression model from sklearn for predicting closing stockes of netflix
from sklearn.linear_model import LinearRegression
algo = LinearRegression()
algo.fit(X_train,Y_train)
Y_predict = algo.predict(X_test)
print(Y_predict)
print(Y.shape)

[498.87622171 294.55659896 338.76758301 273.33076648 288.04594884
 484.6907944  488.68485138 663.31458684 495.72027387 515.02603737
 558.7183525  294.54814014 662.92590796 605.59222596 359.17193771
 305.68996395 477.81363178 514.97096845 367.26984307 499.94285068
 303.8449184  384.54479523 277.17225138 282.83503547 310.44075842
 593.12191738 483.21824561 357.20210877 331.8344207  500.68399874
 540.80639806 352.97405881 450.14828593 375.13113063 331.89750231
 317.72818798 314.4351522  359.12988687 517.80961637 492.58410447
 608.81523878 374.19541221 560.05787644 399.55465562 461.6827648
 434.48576303 357.19998658 629.20383646 345.19496634 686.41933434
 528.76530998 357.56324169 333.17654183 291.56978455 311.95079858
 492.66416285 337.2619389  432.85740717 321.55835939 529.540394
 323.20140385 459.91414311 431.25941996 378.72012347 333.38223386
 552.03536473 341.19528222 517.70661971 358.13120525 391.95532881
 286.57204518 593.16485697 284.12535397 485.32053704 338.82409744
 502.05675643

In [ ]:
#printing score of my model
score = algo.score(X_test,Y_test)
score

In [13]:
df

Open        High         Low    Volume
0     262.000000  267.899994  250.029999  11896100
1     247.699997  266.700012  245.000000  12595800
2     266.579987  272.450012  264.329987   8981500
3     267.079987  267.619995  250.000000   9306700
4     253.850006  255.800003  236.110001  16906900
...          ...         ...         ...       ...
1004  401.970001  427.700012  398.200012  20047500
1005  432.959991  458.480011  425.540009  22542300
1006  448.250000  451.980011  426.480011  14346000
1007  421.440002  429.260010  404.279999   9905200
1008  407.309998  412.769989  396.640015   7782400

[1009 rows x 4 columns]

In [14]:
o = float(input("Enter the opening price : "))
h = float(input("Enter the highest price of the day : "))
l = float(input("Enter the lowest price of the day : "))
v = float(input("Enter the total volume : "))

x_user = np.array([[o,h,l,v]])
y_user = algo.predict(x_user)
print("Closing Price of Stock = ",y_user)

Enter the opening price : 262.0
Enter the highest price of the day : 267.899994
Enter the lowest price of the day : 250.029999
Enter the total volume : 11836100
Closing Price of Stock =  [257.69727851]
